#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_13
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_12
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_14

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_38
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_40

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_14
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_38

#endif

#define BOOT_BUTTON_GPIO        GPIO_NUM_1

#define AHT20_I2C_SDA_PIN       GPIO_NUM_21
#define AHT20_I2C_SCL_PIN       GPIO_NUM_47

#define LIGHT_SENSOR_ADC_GPIO   GPIO_NUM_2

#define BUILTIN_LED_GPIO        GPIO_NUM_45

#define LED_MATRIX_WIDTH        32
#define LED_MATRIX_HEIGHT       8

#endif // _BOARD_CONFIG_H_
